apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-2
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: app
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
