name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        default: staging
        options:
            - production
            - staging

env:
  NAMESPACE: ${{ github.event.inputs.environment == 'production' && 'svc-minecraft' || format('svc-minecraft-${0}', github.event.inputs.environment) }}
  IMAGE: docker.home.valente.ar/svc-minecraft:${{ github.sha }}

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    if: (github.ref == 'refs/heads/main' && github.event.inputs.environment == 'production') || github.event.inputs.environment != 'production'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://docker.home.valente.ar
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade -n ${{ env.NAMESPACE }} --create-namespace --install --wait --set image=${{ env.IMAGE }} -f "./values-${{ github.event.inputs.environment }}.yaml" svc-minecraft ./chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'